version: "3"
services: 
  php:
    build:
      context: docker/php
      args: 
        - ZONE_INFO=${ZONE_INFO}
        - LANG=${LANG}
    image: didix16/php
    volumes:
      - ./:/var/www/app/
    links:
      - db
    networks: 
      - symfony
  nginx:
    build:
      context: docker/nginx
      args:
        - ZONE_INFO=${ZONE_INFO}
        - LANG=${LANG}
    image: didix16/nginx
    volumes:
      - ./:/var/www/app/
      - ./var/logs/nginx:/var/log/nginx
    environment: 
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - 8080:80
      - 4343:443
    links:
      - php
    depends_on:
      - php
    networks:
      - symfony
  db:
    image: mysql:5.6
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3311:3306
    networks: 
      - symfony
networks: 
  symfony: